config mods

diff --git a/source/bxbrio/pkgtools.d/brio-config b/source/bxbrio/pkgtools.d/brio-config
--- a/source/bxbrio/pkgtools.d/brio-config
+++ b/source/bxbrio/pkgtools.d/brio-config
@@ -55,6 +55,7 @@ elif [ -f "${THEPACK_ROOT}/pkgtools.d/package.info"  ]; then
     version=$(cat ${THEPACK_ROOT}/pkgtools.d/package.info | grep "version=" | cut -d'=' -f2 )    
     THEPACK_VERSION=$version
 fi
+THEPACK_LABEL="brio-${THEPACK_VERSION}" 
 
 using_cache_files=0 # default: do not use cache files 
 if [ "x${BRIO_USING_CACHE_FILES}" != "x" ]; then
@@ -64,8 +65,28 @@ if [ "x${BRIO_USING_CACHE_FILES}" != "x" ]; then
 	using_cache_files=1
     fi
 fi
-cflags_cache=${THEPACK_ROOT}/.cflags.cache
-ldflags_cache=${THEPACK_ROOT}/.ldflags.cache
+
+cache_dir=/tmp/${USER}
+if [ ${using_cache_files} -eq 1 ]; then
+    if [ "x${PKGTOOLS_CACHE_DIR}" != "x" ]; then
+	cache_dir=${PKGTOOLS_CACHE_DIR}
+    fi
+    if [ ! -d ${cache_dir} ]; then
+	mkdir -p ${cache_dir}
+	if [ $? -ne 0 ]; then
+	    echo "$SCRIPTNAME: error: Cannot create cache directory !" 1>&2
+	    exit 1
+	fi
+    fi
+fi
+
+cflags_cache=${cache_dir}/.${THEPACK_LABEL}.cflags.cache
+ldflags_cache=${cache_dir}/.${THEPACK_LABEL}.ldflags.cache
+### not sure the right place to do it :
+if [ ${using_cache_files} -eq 0 ]; then
+    test -d ${cflags_cache} && rm -f ${cflags_cache}
+    test -d ${ldflags_cache} && rm -f ${ldflags_cache}
+fi
 
 ldflags_mode=""
 if [ "X${BRIO_LDFLAGS_MODE}" != "X" ]; then
@@ -147,6 +168,7 @@ fi
 
 if [ "x$opt" = "x--cflags" ]; then
     generate_cflags=0
+    cflags_cache_effective=${cflags_cache}
     if [ ${using_cache_files} -eq 1 ]; then
 	if [ -f ${cflags_cache} ]; then
 	    cat ${cflags_cache}
@@ -155,7 +177,9 @@ if [ "x$opt" = "x--cflags" ]; then
 	    generate_cflags=1
 	fi
     else
-	generate_cflags=1
+	test -f ${cflags_cache} && rm -f ${cflags_cache}
+        generate_cflags=1
+	cflags_cache_effective=
     fi
 	    
     if [ ${generate_cflags} -eq 1 ]; then
@@ -167,7 +191,7 @@ if [ "x$opt" = "x--cflags" ]; then
          "`datatools-config --cflags` "  \
          "`root-config --cflags` "  \
 	    ) | python ${THEPACK_ROOT}/pkgtools.d/mkuniqueflags.py	    
-	) | tee ${cflags_cache}
+	) | tee ${cflags_cache_effective}
 	test ${using_cache_files} -eq 0 && rm -f ${cflags_cache}
     fi
     exit 0
@@ -194,6 +218,7 @@ fi
 
 if [ "x$opt" = "x--libs-depends" -o "x$opt" = "x--ldflags" ]; then
     generate_ldflags=0
+    ldflags_cache_effective=${ldflags_cache}
     if [ ${using_cache_files} -eq 1 ]; then
 	if [ -f ${ldflags_cache} ]; then
 	    cat ${ldflags_cache}
@@ -202,7 +227,9 @@ if [ "x$opt" = "x--libs-depends" -o "x$opt" = "x--ldflags" ]; then
 	    generate_ldflags=1
 	fi
     else
-	generate_ldflags=1
+	test -f ${ldflags_cache} && rm -f ${ldflags_cache}
+        generate_ldflags=1
+	ldflags_cache_effective=
     fi
     
     if [ ${generate_ldflags} -eq 1 ]; then	
@@ -217,7 +244,7 @@ if [ "x$opt" = "x--libs-depends" -o "x$opt" = "x--ldflags" ]; then
          "`datatools-config --ldflags` "  \
          "`root-config --libs` "  \
 	    ) | python ${THEPACK_ROOT}/pkgtools.d/mkuniqueflags.py -r
-	) | tee ${ldflags_cache}
+	) | tee ${ldflags_cache_effective}
 	test ${using_cache_files} -eq 0 && rm -f ${ldflags_cache}
     fi
     exit 0
