add multiprocessors to install function

diff --git a/source/bxbrio/pkgtools.d/pkgtool b/source/bxbrio/pkgtools.d/pkgtool
--- a/source/bxbrio/pkgtools.d/pkgtool
+++ b/source/bxbrio/pkgtools.d/pkgtool
@@ -1,11 +1,11 @@
-#!/usr/bin/env bash 
-# -*- mode: shell-script; -*- 
+#!/usr/bin/env bash
+# -*- mode: shell-script; -*-
 # pkgtool
 
 APPNAME="pkgtool"
 
 opwd=$(pwd)
-	
+
 function my_exit ()
 {
     cd ${opwd}
@@ -15,8 +15,8 @@ function my_exit ()
 bio_support=0
 python_wrapper_support=0
 
-appname=${APPNAME} 
-appversion=0.1 
+appname=${APPNAME}
+appversion=0.1
 package_name="brio"
 list_of_actions="check configure unconfigure build doc test untest clean install uninstall reset quickstart list_of_actions"
 pkgtools_dir="pkgtools.d"
@@ -24,16 +24,16 @@ pkgtools_dir="pkgtools.d"
 the_base_dir=$(pwd)
 
 if [ ! -d ./${pkgtools_dir} ]; then
-    echo " ERROR: ${appname}: Please run this script from the package base directory ! Abort !" >&2  
+    echo " ERROR: ${appname}: Please run this script from the package base directory ! Abort !" >&2
     my_exit 1
 fi
 
 libpkgtools_sourced=0
 
 if [ ${libpkgtools_sourced} -eq 0 ]; then
-    libpkgtools_sh=${the_base_dir}/${pkgtools_dir}/libpkgtools.sh 
+    libpkgtools_sh=${the_base_dir}/${pkgtools_dir}/libpkgtools.sh
     if [ -f ${libpkgtools_sh} ]; then
-	source ${libpkgtools_sh}    
+	source ${libpkgtools_sh}
 	libpkgtools_sourced=1
     fi
 fi
@@ -49,7 +49,7 @@ if [ ${libpkgtools_sourced} -eq 0 ]; then
 fi
 
 if [ ${libpkgtools_sourced} -eq 0 ]; then
-    echo " ERROR: ${appname}: Cannot find any 'libpkgtools.sh' setup file ! Abort !" >&2  
+    echo " ERROR: ${appname}: Cannot find any 'libpkgtools.sh' setup file ! Abort !" >&2
     my_exit 1
 fi
 
@@ -79,24 +79,24 @@ function print_usage ()
 
   Options:
 
-    -h 
+    -h
     --help         : print this help then exit
 
     --version      : print version then exit
 
-    -d 
+    -d
     --debug        : print debug mode informations
 
-    -D 
+    -D
     --devel        : print devel mode informations
 
-    -v 
+    -v
     --verbose      : verbose print
 
-    -i      
+    -i
     --interactive  : run in interactive mode (this is the default)
 
-    -b      
+    -b
     --batch        : run in batch mode (no user interaction, disable GUI features)
 
     --no-color     : use un-colored message output
@@ -108,8 +108,8 @@ function print_usage ()
     check               : check dependencies
     configure [OPTIONS] : configure the package
       Options:
-      --install-prefix [INSTALLATION BASE DIRECTORY] : 
-                                   set the installation base directory 
+      --install-prefix [INSTALLATION BASE DIRECTORY] :
+                                   set the installation base directory
                                    (may need special privilege)
 EOF
     if [ ${bio_support} -eq 1 ]; then
@@ -120,7 +120,7 @@ EOF
     fi
     if [ ${python_wrapper_support} -eq 1 ]; then
 	cat <<EOF
-      --with-python-wrapper      : generate the Boost/Python wrapper module 
+      --with-python-wrapper      : generate the Boost/Python wrapper module
       --without-python-wrapper   : do not generate the Boost/Python wrapper module (default)
 EOF
     fi
@@ -131,28 +131,28 @@ EOF
       --without-test             : do not generate test material
       --with-dependency-check    : perform a rudimentary dependency check before processing
       --without-dependency-check : perform a rudimentary dependency check before processing (default)
-      --build-directory [BUILD DIRECTORY] : 
-                                   set the CMake build directory 
-      --reset-build-directory    : always use a brand new CMake build directory 
+      --build-directory [BUILD DIRECTORY] :
+                                   set the CMake build directory
+      --reset-build-directory    : always use a brand new CMake build directory
     unconfigure         : unconfigure the package
     build [OPTIONS]     : build the package
       Options:
-      --number-of-tasks [NUMBER OF TASKS|auto] : 
+      --number-of-tasks [NUMBER OF TASKS|auto] :
                                    use several parallel tasks
-                                   'auto' computes the number of available 
-                                   processors if possible.      
-      
+                                   'auto' computes the number of available
+                                   processors if possible.
+
     doc                 : build documentation
     test                : run test material
     untest              : remove test material
     clean               : clean build material
     install             : install the package
     uninstall           : uninstall the package (not fully implemented yet !)
-    reset               : reset the package's source tree  
+    reset               : reset the package's source tree
     list_of_actions     : print the list of available actions
 
   Examples:
- 
+
     shell> ${appname} check
     shell> ${appname} configure --install-prefix \${HOME}/software
     shell> ${appname} build --number-of-tasks auto
@@ -164,7 +164,7 @@ EOF
     return 0
 }
 
- 
+
 #######################################################
 
 the_action_mode=
@@ -175,7 +175,7 @@ while [ -n "$1" ]; do
     if [ "${token:0:1}" = "-" ]; then
 	opt=${token}
 	if [ ${parse_switch} -eq 0 ]; then
-	    pkgtools__msg_devel "Remaining option '${opt}' !" 
+	    pkgtools__msg_devel "Remaining option '${opt}' !"
 	    break
 	fi
 	if [ "${opt}" = "-h" -o "${opt}" = "--help" ]; then
@@ -198,42 +198,42 @@ while [ -n "$1" ]; do
 	    pkgtools__msg_not_using_color
 	elif [ "${opt}" = "-G" -o "${opt}" = "--gui" ]; then
 	    pkgtools__ui_using_gui
-	    pkgtools__msg_devel "Using GUI" 	
+	    pkgtools__msg_devel "Using GUI"
 	else
-	    pkgtools__msg_error "Invalid option '${opt}' !" 
+	    pkgtools__msg_error "Invalid option '${opt}' !"
 	    my_exit 1
-	    # pkgtools__msg_warning "Ignoring option '${opt}' !" 
+	    # pkgtools__msg_warning "Ignoring option '${opt}' !"
 	fi
     else
 	arg=${token}
 	parse_switch=0
 	if [ "x${the_action_mode}" = "x" ]; then
 	    if [ "$arg" = "check" ]; then
-		the_action_mode="${arg}"	
+		the_action_mode="${arg}"
 	    elif [ "$arg" = "configure" ]; then
-		the_action_mode="${arg}"	
+		the_action_mode="${arg}"
 	    elif [ "$arg" = "unconfigure" ]; then
-		the_action_mode="${arg}"	
+		the_action_mode="${arg}"
             elif [ "$arg" = "build" ]; then
-	        the_action_mode="${arg}"	
+	        the_action_mode="${arg}"
             elif [ "$arg" = "doc" ]; then
-	        the_action_mode="${arg}"	
+	        the_action_mode="${arg}"
             elif [ "$arg" = "test" ]; then
-	        the_action_mode="${arg}"	
+	        the_action_mode="${arg}"
             elif [ "$arg" = "untest" ]; then
-	        the_action_mode="${arg}"	
+	        the_action_mode="${arg}"
             elif [ "$arg" = "install" ]; then
-	        the_action_mode="${arg}"	
+	        the_action_mode="${arg}"
             elif [ "$arg" = "uninstall" ]; then
-	        the_action_mode="${arg}"	
+	        the_action_mode="${arg}"
             elif [ "$arg" = "clean" ]; then
-	        the_action_mode="${arg}"	
+	        the_action_mode="${arg}"
             elif [ "$arg" = "reset" ]; then
-	        the_action_mode="${arg}"	
+	        the_action_mode="${arg}"
             elif [ "$arg" = "quickstart" ]; then
-	        the_action_mode="${arg}"	
+	        the_action_mode="${arg}"
             elif [ "$arg" = "list_of_actions" ]; then
-	        the_action_mode="${arg}"	
+	        the_action_mode="${arg}"
 	    else
 		pkgtools__msg_error "Invalid argument !"
 		my_exit 1
@@ -278,7 +278,7 @@ fi
 function do_check ()
 {
     __pkgtools__at_function_enter do_check
- 
+
     missing_material=""
     missing_material_alt=""
 
@@ -294,7 +294,7 @@ function do_check ()
     if [ $? -ne 0 ]; then
 	missing_material="${missing_material}mygsl "
 	pkgtools__msg_warning "Cannot find mygsl !"
-    else 
+    else
 	pkgtools__msg_notice "Found mygsl $(mygsl-config --version) !"
     fi
 
@@ -343,7 +343,7 @@ function do_configure ()
     while [ -n "$1" ]; do
 	local option="$1"
 	#pkgtools__msg_warning "Option: '${option}'"
-	
+
 	if [ "${option}" = "--build-directory" ]; then
 	    shift 1
 	    the_build_dir="$1"
@@ -399,9 +399,9 @@ function do_configure ()
     fi
 
     pkgtools__msg_notice "Build directory       : '${the_build_dir}'"
-    test -f ${pkgtools_conf} && rm -f ${pkgtools_conf} 
+    test -f ${pkgtools_conf} && rm -f ${pkgtools_conf}
     echo "build_dir=${the_build_dir}" >> ${pkgtools_conf}
- 
+
     pkgtools__msg_notice "Installation prefix   : '${install_prefix}'"
     pkgtools__msg_notice "With documentation    : '${with_doc}'"
     pkgtools__msg_notice "With test material    : '${with_test}'"
@@ -459,8 +459,8 @@ function do_unconfigure ()
     fi
 
     cd ${the_build_dir}
-    test -f CMakeCache.txt && rm -f CMakeCache.txt 
-    test -d CMakeFiles && rm -fr CMakeFiles 
+    test -f CMakeCache.txt && rm -f CMakeCache.txt
+    test -d CMakeFiles && rm -fr CMakeFiles
     cd ${the_base_dir}
 
     if [ -d ${the_build_dir} ]; then
@@ -472,7 +472,7 @@ function do_unconfigure ()
 	pkgtools__msg_notice "Remove the ${pkgtools_conf} configuration file !"
 	rm -f ${pkgtools_conf}
     fi
- 
+
     __pkgtools__at_function_exit
     return 0
 }
@@ -482,7 +482,7 @@ function do_build ()
     __pkgtools__at_function_enter do_build
 
     pkgtools__msg_devel "Options are : '$@'"
-	
+
     if [ ! -d ${the_build_dir} ]; then
 	pkgtools__msg_error "Cannot find the build directory ! Please configure first !"
 	__pkgtools__at_function_exit
@@ -503,9 +503,9 @@ function do_build ()
 	    local number_of_tasks_str="$1"
 	    if [ "x${number_of_tasks_str}" = "xauto" ]; then
 		number_of_tasks=${number_of_processors}
-	    else 
+	    else
 		local number_of_tasks_test=$(echo ${number_of_tasks_str} | tr -d "[0-9]")
-		if [ "x${number_of_tasks_test}" != "x" ]; then 
+		if [ "x${number_of_tasks_test}" != "x" ]; then
 		    pkgtools__msg_error "Invalid number of tasks : ${number_of_tasks_str} !"
 		    __pkgtools__at_function_exit
 		    return 1
@@ -523,14 +523,14 @@ function do_build ()
     pkgtools__msg_notice "Number of tasks : '${number_of_tasks}'"
 
     cd ${the_build_dir}
-    time make --jobs=${number_of_tasks} 
+    time make --jobs=${number_of_tasks}
     if [ $? -ne 0 ]; then
 	pkgtools__msg_error "Cannot build the '${package_name}' package !"
 	__pkgtools__at_function_exit
 	return 1
     fi
     cd ${the_base_dir}
- 
+
     __pkgtools__at_function_exit
     return 0
 }
@@ -565,7 +565,7 @@ function do_test ()
     if [ ! -d ${the_build_dir} ]; then
 	pkgtools__msg_error "Cannot find the build directory ! Please configure and build first !"
 	__pkgtools__at_function_exit
-	return 1	
+	return 1
     fi
 
     cd ${the_build_dir}
@@ -588,7 +588,7 @@ function do_untest ()
     if [ ! -d ${the_build_dir} ]; then
 	pkgtools__msg_error "Cannot find the build directory ! Abort !"
 	__pkgtools__at_function_exit
-	return 1	
+	return 1
     fi
 
     cd ${the_build_dir}
@@ -629,11 +629,43 @@ function do_install ()
     if [ ! -d ${the_build_dir} ]; then
 	pkgtools__msg_error "Cannot find the build directory ! Please configure and build first !"
 	__pkgtools__at_function_exit
-	return 1	
+	return 1
+    fi
+    local number_of_tasks=0
+    local number_of_processors=1
+    pkgtools__knows_number_of_processors
+    if [ $? -eq 0 ]; then
+	number_of_processors=$(pkgtools__get_number_of_processors)
+    fi
+    while [ -n "$1" ]; do
+	local option="$1"
+	pkgtools__msg_devel "Build option: '${option}'"
+	if [ "${option}" = "--number-of-tasks" ]; then
+	    shift 1
+	    local number_of_tasks_str="$1"
+	    if [ "x${number_of_tasks_str}" = "xauto" ]; then
+		number_of_tasks=${number_of_processors}
+	    else
+		local number_of_tasks_test=$(echo ${number_of_tasks_str} | tr -d "[0-9]")
+		if [ "x${number_of_tasks_test}" != "x" ]; then
+		    pkgtools__msg_error "Invalid number of tasks : ${number_of_tasks_str} !"
+		    __pkgtools__at_function_exit
+		    return 1
+		fi
+		number_of_tasks=${number_of_tasks_str}
+	    fi
+	fi
+	shift 1
+    done
+
+    if [ ${number_of_tasks} -eq 0 ]; then
+	number_of_tasks=${number_of_processors}
     fi
 
+    pkgtools__msg_notice "Number of tasks : '${number_of_tasks}'"
+
     cd ${the_build_dir}
-    make install
+    make --jobs=${number_of_tasks} install
     if [ $? -ne 0 ]; then
 	pkgtools__msg_error "Cannot install the '${package_name}' package !"
 	__pkgtools__at_function_exit
@@ -661,12 +693,12 @@ function do_uninstall ()
 	    return 0
 	fi
     fi
-        
+
     local try_uninstall=1
     if [ ${try_uninstall} -eq 1 ]; then
 	local the_install_prefix=$(get_install_prefix_from_cmake)
 	if [ "x${the_install_prefix}" != "x" ]; then
-	    pkgtools__msg_notice "Installation prefix is : ${the_install_prefix}"	    
+	    pkgtools__msg_notice "Installation prefix is : ${the_install_prefix}"
 	else
 	    pkgtools__msg_error "No installation prefix could be extracted from CMake build directory !"
 	    __pkgtools__at_function_exit
@@ -676,51 +708,51 @@ function do_uninstall ()
 	if [ -d ${the_install_prefix} ]; then
 	    test -w ${the_install_prefix}
 	    if [ $? -ne 0 ]; then
-		pkgtools__msg_error "You don't have proper permission for the installation base directory '${the_install_prefix}' !"	
+		pkgtools__msg_error "You don't have proper permission for the installation base directory '${the_install_prefix}' !"
 		__pkgtools__at_function_exit
 		return 1
 	    else
-		pkgtools__msg_devel "You do have proper permission for the installation base directory '${the_install_prefix}' !"	
+		pkgtools__msg_devel "You do have proper permission for the installation base directory '${the_install_prefix}' !"
 	    fi
 	else
-	    pkgtools__msg_error "There is no installation base directory to be uninstalled !"	
+	    pkgtools__msg_error "There is no installation base directory to be uninstalled !"
 	    __pkgtools__at_function_exit
 	    return 1
 	fi
 
 	if [ -f ${the_build_dir}/install_manifest.txt ]; then
-	    pkgtools__msg_notice "Removing all installed files..."	    
+	    pkgtools__msg_notice "Removing all installed files..."
 	    local list_of_entries=$(cat ${the_build_dir}/install_manifest.txt)
 	    for entry in ${list_of_entries}; do
 		if [ -f ${entry} ]; then
-		    pkgtools__msg_devel "Removing installed file '${entry}'..."	
+		    pkgtools__msg_devel "Removing installed file '${entry}'..."
 		    rm -f ${entry}
 		fi
 	    done
-	    pkgtools__msg_notice "All installed files have been removed !"	
+	    pkgtools__msg_notice "All installed files have been removed !"
 	else
-	    pkgtools__msg_warning "It seems there is no file to be uninstalled !"		    
- 	fi 
+	    pkgtools__msg_warning "It seems there is no file to be uninstalled !"
+ 	fi
 
 	if [ "x${the_install_prefix}" != "x" ]; then
 	    if [ -d ${the_install_prefix} ]; then
 		local the_list_of_dirs=$(find ${the_install_prefix} -mindepth 1 -type d | sort -r)
-		pkgtools__msg_devel "The list of subdirectories : '${the_list_of_dirs}'"	
+		pkgtools__msg_devel "The list of subdirectories : '${the_list_of_dirs}'"
 		for dir in ${the_list_of_dirs}; do
 		    local dir_count=$(ls -a -1 ${dir}/ | wc -l)
 		    let dir_count=dir_count-2
-		    pkgtools__msg_devel "Installation subdirectory '${dir}' has ${dir_count} entries"	
-		    if [ ${dir_count} -eq 0 ]; then 
-			pkgtools__msg_devel "Removing empty installation subdirectory '${dir}'..."	
+		    pkgtools__msg_devel "Installation subdirectory '${dir}' has ${dir_count} entries"
+		    if [ ${dir_count} -eq 0 ]; then
+			pkgtools__msg_devel "Removing empty installation subdirectory '${dir}'..."
 			rmdir ${dir}
 		    fi
 		done
 		local base_dir_count=$(ls -a -1 ${the_install_prefix}/ | wc -l)
 		let base_dir_count=base_dir_count-2
-		if [ ${base_dir_count} -eq 0 ]; then 
-		    pkgtools__msg_devel "Removing empty installation base directory '${the_install_prefix}'..."	
+		if [ ${base_dir_count} -eq 0 ]; then
+		    pkgtools__msg_devel "Removing empty installation base directory '${the_install_prefix}'..."
 		    rmdir ${the_install_prefix}
-		    pkgtools__msg_notice "The empty installation base directory '${the_install_prefix}' has been removed !"	
+		    pkgtools__msg_notice "The empty installation base directory '${the_install_prefix}' has been removed !"
 		fi
 	    fi
 	fi
@@ -737,7 +769,7 @@ function do_clean ()
     if [ ! -d ${the_build_dir} ]; then
 	pkgtools__msg_error "Cannot find the build directory ! Abort !"
 	__pkgtools__at_function_exit
-	return 1	
+	return 1
     fi
 
     cd ${the_build_dir}
@@ -750,7 +782,7 @@ function do_clean ()
     cd ${the_base_dir}
 
     __pkgtools__at_function_exit
-    return 0    
+    return 0
 }
 
 function do_reset ()
@@ -761,32 +793,32 @@ function do_reset ()
     if [ $? -ne 0 ]; then
 	pkgtools__msg_warning "Could not uninstall the '${package_name}' package !"
 	# __pkgtools__at_function_exit
-	# return 1	
+	# return 1
     fi
 
     do_untest
     if [ $? -ne 0 ]; then
 	pkgtools__msg_warning "Could not clean test material in the '${package_name}' package !"
 	# __pkgtools__at_function_exit
-	# return 1	
+	# return 1
     fi
 
     do_clean
     if [ $? -ne 0 ]; then
 	pkgtools__msg_warning "Could not clean the '${package_name}' package !"
 	# __pkgtools__at_function_exit
-	# return 1	
+	# return 1
     fi
 
     do_unconfigure
     if [ $? -ne 0 ]; then
 	pkgtools__msg_warning "Could not unconfigure the '${package_name}' package !"
 	# __pkgtools__at_function_exit
-	# return 1	
+	# return 1
     fi
 
     __pkgtools__at_function_exit
-    return 0    
+    return 0
 }
 
 function main ()
@@ -804,7 +836,7 @@ function main ()
 	return 1
     fi
 
-    # Perform actions :    
+    # Perform actions :
     if [ "${action_mode}" = "check" ]; then
 	do_check $@
 	if [ $? -ne 0 ]; then
@@ -813,7 +845,7 @@ function main ()
 	    return 1
 	fi
     fi
-    
+
     if [ "${action_mode}" = "configure" ]; then
 	do_configure $@
 	if [ $? -ne 0 ]; then
@@ -822,7 +854,7 @@ function main ()
 	    return 1
 	fi
     fi
-    
+
     if [ "${action_mode}" = "unconfigure" ]; then
 	do_unconfigure $@
 	if [ $? -ne 0 ]; then
@@ -831,7 +863,7 @@ function main ()
 	    return 1
 	fi
     fi
-    
+
     if [ "${action_mode}" = "build" ]; then
 	do_build $@
 	if [ $? -ne 0 ]; then
@@ -840,7 +872,7 @@ function main ()
 	    return 1
 	fi
     fi
-    
+
     if [ "${action_mode}" = "doc" ]; then
 	do_doc $@
 	if [ $? -ne 0 ]; then
@@ -849,7 +881,7 @@ function main ()
 	    return 1
 	fi
     fi
-    
+
     if [ "${action_mode}" = "test" ]; then
 	do_test $@
 	if [ $? -ne 0 ]; then
@@ -858,7 +890,7 @@ function main ()
 	    return 1
 	fi
     fi
-    
+
     if [ "${action_mode}" = "untest" ]; then
 	do_untest $@
 	if [ $? -ne 0 ]; then
@@ -867,7 +899,7 @@ function main ()
 	    return 1
 	fi
     fi
-    
+
     if [ "${action_mode}" = "install" ]; then
 	do_install $@
 	if [ $? -ne 0 ]; then
@@ -876,7 +908,7 @@ function main ()
 	    return 1
 	fi
     fi
-    
+
     if [ "${action_mode}" = "uninstall" ]; then
 	do_uninstall $@
 	if [ $? -ne 0 ]; then
@@ -885,7 +917,7 @@ function main ()
 	    return 1
 	fi
     fi
-    
+
     if [ "${action_mode}" = "clean" ]; then
 	do_clean $@
 	if [ $? -ne 0 ]; then
@@ -894,16 +926,16 @@ function main ()
 	    return 1
 	fi
     fi
-    
+
     if [ "${action_mode}" = "quickstart" ]; then
-	do_configure $@ && do_build $@ && do_doc $@ && do_test && do_install 
+	do_configure $@ && do_build $@ && do_doc $@ && do_test && do_install
 	if [ $? -ne 0 ]; then
 	    pkgtools__msg_error "Quickstart failed !"
 	    __pkgtools__at_function_exit
 	    return 1
 	fi
     fi
-   
+
     if [ "${action_mode}" = "reset" ]; then
 	do_reset $@
 	if [ $? -ne 0 ]; then
@@ -912,11 +944,11 @@ function main ()
 	    return 1
 	fi
     fi
-   
+
     if [ "${action_mode}" = "list_of_actions" ]; then
-	echo ${list_of_actions} 
+	echo ${list_of_actions}
     fi
-  
+
     __pkgtools__at_function_exit
     return 0
 }
