config mods

diff --git a/source/bxdatatools/pkgtools.d/datatools-config b/source/bxdatatools/pkgtools.d/datatools-config
--- a/source/bxdatatools/pkgtools.d/datatools-config
+++ b/source/bxdatatools/pkgtools.d/datatools-config
@@ -57,6 +57,7 @@ elif [ -f "$THEPACK_ROOT/pkgtools.d/package.info"  ]; then
     version=$(cat $THEPACK_ROOT/pkgtools.d/package.info | grep "version=" | cut -d'=' -f2 )    
     THEPACK_VERSION=${version}
 fi
+THEPACK_LABEL="datatools-${THEPACK_VERSION}" 
 
 #echo "DATATOOLS_USING_CACHE_FILES=${DATATOOLS_USING_CACHE_FILES}" 1>&2
 
@@ -71,8 +72,23 @@ fi
 
 #echo "$SCRIPTNAME: warning: using cache files = ${using_cache_files}" 1>&2
 
-cflags_cache=${THEPACK_ROOT}/.cflags.cache
-ldflags_cache=${THEPACK_ROOT}/.ldflags.cache
+cache_dir=/tmp/${USER}
+if [ ${using_cache_files} -eq 1 ]; then
+    if [ "x${PKGTOOLS_CACHE_DIR}" != "x" ]; then
+	cache_dir=${PKGTOOLS_CACHE_DIR}
+    fi
+    if [ ! -d ${cache_dir} ]; then
+	mkdir -p ${cache_dir}
+	if [ $? -ne 0 ]; then
+	    echo "$SCRIPTNAME: error: Cannot create cache directory !" 1>&2
+	    exit 1
+	fi
+    fi
+fi
+
+cflags_cache=${cache_dir}/.${THEPACK_LABEL}.cflags.cache
+ldflags_cache=${cache_dir}/.${THEPACK_LABEL}.ldflags.cache
+### not sure the right place to do it :
 if [ ${using_cache_files} -eq 0 ]; then
     test -d ${cflags_cache} && rm -f ${cflags_cache}
     test -d ${ldflags_cache} && rm -f ${ldflags_cache}
@@ -189,6 +205,7 @@ fi
 
 if [ "x$opt" = "x--cflags" ]; then
     generate_cflags=0
+    cflags_cache_effective=${cflags_cache}
     if [ ${using_cache_files} -eq 1 ]; then
         if [ -f ${cflags_cache} ]; then
             cat ${cflags_cache}
@@ -199,6 +216,7 @@ if [ "x$opt" = "x--cflags" ]; then
     else
 	test -f ${cflags_cache} && rm -f ${cflags_cache}
         generate_cflags=1
+	cflags_cache_effective=
     fi
 
     if [ ${generate_cflags} -eq 1 ]; then
@@ -225,7 +243,7 @@ if [ "x$opt" = "x--cflags" ]; then
 		fi
 		echo -n "`clhep-config --include` " 
 	    ) | python ${THEPACK_ROOT}/pkgtools.d/mkuniqueflags.py 
-	) | tee ${cflags_cache}
+	) | tee ${cflags_cache_effective}
 	test ${using_cache_files} -eq 0 && rm -f ${cflags_cache}
     fi
     exit 0
@@ -252,6 +270,7 @@ fi
 
 if [ "x$opt" = "x--libs-depends" -o "x$opt" = "x--ldflags" ]; then
     generate_ldflags=0
+    ldflags_cache_effective=${ldflags_cache}
     if [ ${using_cache_files} -eq 1 ]; then
         if [ -f ${ldflags_cache} ]; then
             cat ${ldflags_cache}
@@ -262,6 +281,7 @@ if [ "x$opt" = "x--libs-depends" -o "x$opt" = "x--ldflags" ]; then
     else
 	test -f ${ldflags_cache} && rm -f ${ldflags_cache}
         generate_ldflags=1
+	ldflags_cache_effective=
     fi
     
     if [ ${generate_ldflags} -eq 1 ]; then      
@@ -277,7 +297,7 @@ if [ "x$opt" = "x--libs-depends" -o "x$opt" = "x--ldflags" ]; then
 		echo -n "`boost-config --ldflags serialization iostreams filesystem system` " 
 		echo -n "`clhep-config --libs` -lm "
             ) | python ${THEPACK_ROOT}/pkgtools.d/mkuniqueflags.py -r 
-	) | tee ${ldflags_cache}
+	) | tee ${ldflags_cache_effective}
 	test ${using_cache_files} -eq 0 && rm -f ${ldflags_cache}
     fi
     exit 0
