merge dev0 in trunk, add serializable histogram_pool class

diff --git a/source/bxmygsl/cmake/Templates/mygsl-config.in b/source/bxmygsl/cmake/Templates/mygsl-config.in
--- a/source/bxmygsl/cmake/Templates/mygsl-config.in
+++ b/source/bxmygsl/cmake/Templates/mygsl-config.in
@@ -1,19 +1,27 @@
 #!/usr/bin/env bash
 # -*- mode: shell-script; -*-
 # mygsl-config
-##
+#
 
 script_name="mygsl-config"
 
 opwd=$(pwd)
 help=0
 debug=0
-bio_support=0
-python_wrapper_support=0
+devel=0
+#bio_support=1
+#python_wrapper_support=0
+bio_support=@MYGSL_WITH_BIO_SUPPORT@
+python_wrapper_support=@MYGSL_WITH_PYTHON_WRAPPER_SUPPORT@
+
+with_debug=0
+if [ "x@MYGSL_WITH_DEBUG@" == "x1" -o "x@MYGSL_WITH_DEBUG@" == "xON" ]; then
+    with_debug=1
+fi
 
 if [ ${python_wrapper_support} -eq 1 ]; then
     with_python_wrapper=0
-    if [ "x@MYGSL_WITH_PYTHON_WRAPPER@" == "x1"  -o "x@MYGSL_WITH_PYTHON_WRAPPER@" == "xON" ]; then
+    if [ "x@MYGSL_WITH_PYTHON_WRAPPER@" == "x1" -o "x@MYGSL_WITH_PYTHON_WRAPPER@" == "xON" ]; then
 	with_python_wrapper=1
     fi
 fi
@@ -25,9 +33,21 @@ if [ ${bio_support} -eq 1 ]; then
     fi
 fi
 
-with_debug=0
-if [ "x@MYGSL_WITH_DEBUG@" == "x1" -o "x@MYGSL_WITH_DEBUG@" == "xON" ]; then
-    with_debug=1
+with_automated_dependecies=0
+if [ "x@AUTOMATIC_CMAKE_DEPENDENCIES@" == "x1" -o "x@AUTOMATIC_CMAKE_DEPENDENCIES@" == "xON" ]; then
+    with_automated_dependecies=1
+fi
+
+if [ ${with_automated_dependecies} -eq 1 ]; then
+    list_of_third_party_dependencies_infos=$(echo "@_mygsl_list_of_third_party_dependencies_infos@" | tr -d [[:space:]] | tr ';' ' ')
+    list_of_dependencies_infos=$(echo "@_mygsl_list_of_dependencies_infos@" | tr -d [[:space:]] | tr ';' ' ')
+    full_list_of_dependencies_infos=
+    if [ "x${list_of_dependencies_infos}" != "x" ]; then
+	full_list_of_dependencies_infos="${full_list_of_dependencies_infos}${list_of_dependencies_infos} "
+    fi
+    if [ "x${list_of_third_party_dependencies_infos}" != "x" ]; then
+	full_list_of_dependencies_infos="${full_list_of_dependencies_infos}${list_of_third_party_dependencies_infos}"
+    fi
 fi
 
 function my_exit ()
@@ -38,19 +58,19 @@ function my_exit ()
 
 mygsl_system="@CMAKE_SYSTEM_NAME@-@CMAKE_SYSTEM_PROCESSOR@"
 
-mygsl_root=@CMAKE_INSTALL_PREFIX@
+mygsl_root="@CMAKE_INSTALL_PREFIX@"
 
-mygsl_include_dir="${mygsl_root}/@CMAKE_INSTALL_INCLUDEDIR@"
+mygsl_include_dir="@CMAKE_INSTALL_FULL_INCLUDEDIR@"
 
-mygsl_lib_dir="${mygsl_root}/@CMAKE_INSTALL_LIBDIR@"
+mygsl_lib_dir="@CMAKE_INSTALL_FULL_LIBDIR@"
 
-mygsl_bin_dir="${mygsl_root}/@CMAKE_INSTALL_BINDIR@"
+mygsl_bin_dir="@CMAKE_INSTALL_FULL_BINDIR@"
 
-mygsl_data_dir="@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_DATADIR@"
+mygsl_data_dir="@CMAKE_INSTALL_FULL_DATADIR@"
 
-mygsl_etc_dir="@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_ETCDIR@"
+mygsl_etc_dir="@CMAKE_INSTALL_FULL_ETCDIR@"
 
-mygsl_doc_dir="@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_DOCDIR@"
+mygsl_doc_dir="@CMAKE_INSTALL_FULL_DOCDIR@"
 
 mygsl_cmake_config_dir="@CMAKE_INSTALL_PREFIX@/@mygsl_cmake_config_install_dir@"
 
@@ -92,14 +112,18 @@ Known values for OPTION are:
 EOF
     if [ ${bio_support} -eq 1 ]; then
 	cat<<EOF
+  --with-bio            print if Boost/Serialization binary code is pre-built 
+                        in an auxiliary I/O shared library
+EOF
+    fi
+    if [ ${bio_support} -eq 1 ]; then
+	cat<<EOF
   --libs     [option]   print library linking information, without dependencies
   --ldflags  [option]   print library linking information, with dependencies
       Options: --with-bio     with linkage against the libmygsl_bio.so DLL (default)
                --without-bio  without linkage against the libmygsl_bio.so DLL
-  --with-bio            print if Boost/Serialization binary code is pre-built 
-                        in an auxiliary I/O shared library
 EOF
-    else
+    else  
 	cat<<EOF
   --libs                print library linking information, without dependencies
   --ldflags             print library linking information, with dependencies
@@ -114,13 +138,13 @@ EOF
   --with-debug          print if mygsl has been compiled in 'debug' mode
   --cmake-config-dir    print the installation directory for the 'mygsl-config.cmake' file
 EOF
-    cat<<EOF
-  --datatools-version   print datatools version
-  --gsl-version         print GSL version
+    if [ ${with_automated_dependecies} -eq 1 ]; then
+	cat<<EOF
+  --list-of-dependencies print the list of known auto-resolved dependencies
 EOF
+    fi
     return 0
 }
-
 
 if [ ${help} -eq 1 ]; then
     print_help
@@ -152,11 +176,6 @@ if [ "x${option}" = "x--include-dir" -o "x${option}" = "x--incdir" ]; then
     my_exit 0
 fi
 
-if [ "x${option}" = "x--docdir" ]; then
-    echo "${mygsl_doc_dir}"
-    my_exit 0
-fi
-
 if [ "x${option}" = "x--datadir" ]; then
     echo "${mygsl_data_dir}"
     my_exit 0
@@ -167,19 +186,82 @@ if [ "x${option}" = "x--etcdir" ]; then
     my_exit 0
 fi
 
+if [ "x${option}" = "x--docdir" ]; then
+    echo "${mygsl_doc_dir}"
+    my_exit 0
+fi
+
+if [ "x${option}" = "x--resources-dir" ]; then
+    echo "${mygsl_resources_dir}"
+    my_exit 0
+fi
+
 if [ "x${option}" = "x--include" ]; then
     echo "-I${mygsl_include_dir} "
     my_exit 0
 fi
 
+if [ ${with_automated_dependecies} -eq 1 ]; then
+    if [ "x${option}" = "x--list-of-dependencies" ]; then
+	echo "${full_list_of_dependencies_infos}"
+	my_exit 0
+    fi
+fi
+
 if [ "x${option}" = "x--cflags" ]; then
     (
 	echo -n "-fPIC " 
-	echo -n "-I${mygsl_include_dir} "  
-	echo -n "`datatools-config --cflags` "
-	echo -n "`gsl-config --cflags` "
+	echo -n "-I${mygsl_include_dir} "
+        #
+        # Automated dependencies (experimental)
+        #
+	if [ ${with_automated_dependecies} -eq 1 ]; then  
+	    for dependency_info in ${full_list_of_dependencies_infos}; do
+		if [ ${devel} -gt 0 ]; then
+		    echo "DEVEL: ${script_name}: Processing automatic dependency info '${dependency_info}' script !" 1>&2
+		fi
+		dependency_name=$(echo ${dependency_info} | cut -d':' -f1)
+		dependency_version=$(echo ${dependency_info} | cut -d':' -f2)
+		dependency_name_lower=$(echo ${dependency_name} | tr "A-Z" "a-z" )
+		dependency_name_upper=$(echo ${dependency_name} | tr "a-z" "A-Z" )
+		dependency_no_config_script_ENVNAME="${dependency_name_upper}_NO_CONFIG_SCRIPT"
+		if [ "x${!dependency_no_config_script_ENVNAME}" = "x1" ]; then
+		    continue
+		fi
+		dependency_config_script="${dependency_name_lower}-config"
+		dependency_config_script_ENVNAME="${dependency_name_upper}_CONFIG_SCRIPT"
+		if [ "x${!dependency_config_script_ENVNAME}" != "x" ]; then
+		    dependency_config_script="${!dependency_config_script_ENVNAME}"
+		fi
+		which ${dependency_config_script} >/dev/null 2>&1
+		if [ $? -eq 0 ]; then
+		    cflags_switch="--cflags"
+		    dependency_config_script_cflags_switch_ENVNAME="${dependency_name_upper}_CONFIG_SCRIPT_DEFAULT_CFLAGS_SWITCH"
+		    if [ "x${!dependency_config_script_cflags_switch_ENVNAME}" != "x" ]; then
+			###echo "DEVEL: ${script_name}: dependency_config_script_cflags_switch == '${!dependency_config_script_cflags_switch_ENVNAME}' !" 1>&2
+			cflags_switch="${!dependency_config_script_cflags_switch}"
+		    fi
+		    if [ "x${cflags_switch}" != "x" ]; then
+			dependency_cflags=$(${dependency_config_script} ${cflags_switch} | tr '\n' ' ')
+			if [ $? -ne 0 ]; then
+			    dependency_cflags=
+			    echo "ERROR: ${script_name}: No support for the '${cflags_switch}' switch from the '${dependency_config_script}' script !" 1>&2
+			    my_exit 1
+			fi
+			echo -n "${dependency_cflags} "
+		    fi
+		else 
+		    echo "ERROR: ${script_name}: No support for a '${dependency_config_script}' script !" 1>&2
+		    echo "ERROR: ${script_name}: You may consider to fix the 'mygsl-config.in' template script manually !" 1>&2
+		    my_exit 1
+		fi
+	    done
+	fi
+        #
+        # Here one can add more dependency material
+        #
 	echo ""
-    ) | python @CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_DATADIR@/pkgtools/mkuniqueflags.py 
+    ) | python ${mygsl_data_dir}/pkgtools/mkuniqueflags.py     
     my_exit 0
 fi
 
@@ -196,21 +278,21 @@ fi
 more_ldflags=
 # compute default linkage :
 if [ ${bio_support} -eq 1 ]; then
-  bio_ldflags=
-  if [ ${with_bio} -eq 1 ]; then
-      bio_ldflags=-lmygsl_bio
-  fi
+    bio_ldflags=
+    if [ ${with_bio} -eq 1 ]; then
+	bio_ldflags=-lmygsl_bio
+    fi
 fi
- 
+
 if [ "x${option}" = "x--libs" ]; then
     if [ ${bio_support} -eq 1 ]; then
-      if [ "x${option2}" = "x--without-bio" ]; then
-     	bio_ldflags=
-      fi
-      if [ "x${option2}" = "x--with-bio" -a ${with_bio} -eq 1 ]; then
-     	bio_ldflags=-lmygsl_bio
-      fi
-      more_ldflags="${more_ldflags} ${bio_ldflags} "
+	if [ "x${option2}" = "x--without-bio" ]; then
+     	    bio_ldflags=
+	fi
+	if [ "x${option2}" = "x--with-bio" -a ${with_bio} -eq 1 ]; then
+     	    bio_ldflags=-lmygsl_bio
+	fi
+	more_ldflags="${more_ldflags} ${bio_ldflags} "
     fi
     echo -n "-L${mygsl_lib_dir} ${more_ldflags} -lmygsl "
     echo
@@ -223,16 +305,61 @@ if [ "x${option}" = "x--ldflags" ]; then
     	    bio_ldflags=
 	fi
 	if [ "x${option2}" = "x--with-bio" -a ${with_bio} -eq 1 ]; then
-    	bio_ldflags=-lmygsl_bio
+    	    bio_ldflags=-lmygsl_bio
 	fi
 	more_ldflags="${more_ldflags} ${bio_ldflags} "
     fi
     (
 	echo -n "-L${mygsl_lib_dir} ${more_ldflags} -lmygsl "
-	echo -n "`datatools-config --ldflags` "
-	echo -n "`gsl-config --libs` "
+        #
+        # Automated dependencies (experimental)
+        #
+	if [ ${with_automated_dependecies} -eq 1 ]; then  
+	    for dependency_info in ${full_list_of_dependencies_infos}; do
+		if [ ${devel} -gt 0 ]; then
+		    echo "DEVEL: ${script_name}: Processing automatic dependency info '${dependency_info}' script !" 1>&2
+		fi
+		dependency_name=$(echo ${dependency_info} | cut -d':' -f1)
+		dependency_version=$(echo ${dependency_info} | cut -d':' -f2)
+		dependency_name_lower=$(echo ${dependency_name} | tr "A-Z" "a-z" )
+		dependency_name_upper=$(echo ${dependency_name} | tr "a-z" "A-Z" )
+		dependency_no_config_script_ENVNAME="${dependency_name_upper}_NO_CONFIG_SCRIPT"
+		if [ "x${!dependency_no_config_script_ENVNAME}" = "x1" ]; then
+		    continue
+		fi
+		dependency_config_script="${dependency_name_lower}-config"
+		dependency_config_script_ENVNAME="${dependency_name_upper}_CONFIG_SCRIPT"
+		if [ "x${!dependency_config_script_ENVNAME}" != "x" ]; then
+		    dependency_config_script="${!dependency_config_script_ENVNAME}"
+		fi
+		which ${dependency_config_script} >/dev/null 2>&1
+		if [ $? -eq 0 ]; then
+		    ldflags_switch="--ldflags"
+		    dependency_config_script_ldflags_switch_ENVNAME="${dependency_name_upper}_CONFIG_SCRIPT_DEFAULT_LDFLAGS_SWITCH"
+		    if [ "x${!dependency_config_script_ldflags_switch_ENVNAME}" != "x" ]; then
+			ldflags_switch="${!dependency_config_script_ldflags_switch_ENVNAME}"
+			###echo "DEVEL: ${script_name}: dependency_config_script_ldflags_switch == '${dependency_config_script_ldflags_switch_ENVNAME}' !" 1>&2
+		    fi
+		    if [ "x${ldflags_switch}" != "x" ]; then
+			dependency_ldflags=$(${dependency_config_script} ${ldflags_switch} | tr '\n' ' ')
+			if [ $? -ne 0 ]; then
+			    dependency_ldflags=
+			    echo "ERROR: ${script_name}: No support for the '${ldflags_switch}' switch from the '${dependency_config_script}' script !" 1>&2
+			    my_exit 1
+			fi
+			echo -n "${dependency_ldflags} "
+		    fi
+		else
+		    echo "WARNING: ${script_name}: No support for a '${dependency_config_script}' script !" 1>&2
+		    echo "WARNING: ${script_name}: You may consider to fix the 'mygsl-config.in' template script manually !" 1>&2
+		fi
+	    done
+	fi
+        #
+        # here one can add more dependency material
+        #
 	echo ""
-    ) | python @CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_DATADIR@/pkgtools/mkuniqueflags.py -r
+    ) | python ${mygsl_data_dir}/pkgtools/mkuniqueflags.py -r   
     my_exit 0
 fi
 
@@ -265,16 +392,6 @@ if [ ${python_wrapper_support} -eq 1 ]; then
 	    my_exit 1	
 	fi
     fi
-fi
-
-if [ "x${option}" = "x--datatools-version" ]; then
-    echo @DATATOOLS_VERSION@
-    my_exit 0
-fi
-
-if [ "x${option}" = "x--gsl-version" ]; then
-    echo @GSL_VERSION@
-    my_exit 0
 fi
 
 echo "ERROR: ${script_name}: Unknown option !" 1>&2
