improvement of the CMake build layer, embedded kwsys, buf fixes (still preliminary)

diff --git a/source/bxdatatools/cmake/templates/datatools-config.in b/source/bxdatatools/cmake/templates/datatools-config.in
--- a/source/bxdatatools/cmake/templates/datatools-config.in
+++ b/source/bxdatatools/cmake/templates/datatools-config.in
@@ -12,43 +12,47 @@ debug=0
 function my_exit ()
 {
     cd ${opwd}
-    exit $?
+    exit $1
 }
 
 datatools_system="@CMAKE_SYSTEM_NAME@-@CMAKE_SYSTEM_PROCESSOR@"
 
 datatools_root=@CMAKE_INSTALL_PREFIX@
 
-if [ -n "${DATATOOLS_ROOT}" ]; then
-    datatools_root="${DATATOOLS_ROOT}"
-else
-    echo "ERROR: ${script_name}: 'DATATOOLS_ROOT' environment variable is not defined ! Abort !" 1>&2
-    my_exit 1
-fi
+# if [ -n "${DATATOOLS_ROOT}" ]; then
+#     datatools_root="${DATATOOLS_ROOT}"
+# else
+#     echo "ERROR: ${script_name}: 'DATATOOLS_ROOT' environment variable is not defined ! Abort !" 1>&2
+#     my_exit 1
+# fi
 
-datatools_include_dir="${datatools_root}/include"
+datatools_bin_dir="${datatools_root}/@CMAKE_INSTALL_BINDIR@"
 
-datatools_lib_dir="${datatools_root}/lib"
+datatools_lib_dir="${datatools_root}/@CMAKE_INSTALL_LIBDIR@"
 
-datatools_bin_dir="${datatools_root}/bin"
+datatools_etc_dir="${datatools_root}/@CMAKE_INSTALL_ETCDIR@"
 
-datatools_resources_dir="@CMAKE_INSTALL_PREFIX@/@INSTALL_RESOURCES_DIR@"
+datatools_doc_dir="${datatools_root}/@CMAKE_INSTALL_DOCDIR@"
+
+datatools_include_dir="${datatools_root}/@CMAKE_INSTALL_INCLUDEDIR@"
+
+datatools_data_dir="@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_DATADIR@"
 
 datatools_version=@datatools_VERSION_STR@
 
 with_python_wrapper=0
-if [ "x@DATATOOLS_WITH_PYTHON_WRAPPER@" == "x1" ]; then
+if [ "x@DATATOOLS_WITH_PYTHON_WRAPPER@" == "x1" -o "x@DATATOOLS_WITH_PYTHON_WRAPPER@" == "xON" ]; then
     with_python_wrapper=1
 fi
 
-with_bio=0
-if [ "x@DATATOOLS_WITH_BIO@" == "x1" ]; then
-    with_bio=1
+with_debug=0
+if [ "x@DATATOOLS_WITH_DEBUG@" == "x1" -o "x@DATATOOLS_WITH_DEBUG@" == "xON" ]; then
+    with_debug=1
 fi
 
-with_embedded_kwsys=0
-if [ "x@DATATOOLS_WITH_EMBEDDED_KWSYS@" == "x1" ]; then
-    with_embedded_kwsys=1
+with_bio=0
+if [ "x@DATATOOLS_WITH_BIO@" == "x1" -o "x@DATATOOLS_WITH_BIO@" == "xON" ]; then
+    with_bio=1
 fi
 
 option="$1"
@@ -75,10 +79,12 @@ Known values for OPTION are:
   --version             print version information
   --system              print system
   --prefix              print datatools installation prefix
-  --incdir              print include directory
-  --libdir              print library directory
   --bindir              print binary directory
-  --resources-dir       print resources directory
+  --libdir              print library directory
+  --incdir              print include directory
+  --datadir             print data directory
+  --docdir              print documentation directory
+  --etcdir              print data directory
   --include             print include path pre-processor flags without dependencies
   --cflags              print include path pre-processor flags with dependencies
   --libs    [option]    print library linking information, without dependencies
@@ -88,7 +94,7 @@ Known values for OPTION are:
   --with-python-wrapper print if Python wrapper module is used
   --with-bio            print if Boost/Serialization binary code is pre-built 
                         in an auxiliary I/O shared library
-  --with-embedded-kwsys print if Kwsys is embedded in datatools
+  --with-debug          print if datatools has been compiled in 'debug' mode
   --boost-version       print Boost version
   --clhep-version       print CLHEP version
 
@@ -111,13 +117,23 @@ if [ "x${option}" = "x--version" ]; then
     my_exit 0
 fi
 
-if [ "x${option}" = "x--include-dir" -o "x${option}" = "x--incdir" ]; then
+if [ "x${option}" = "x--incdir" ]; then
     echo "${datatools_include_dir}"
     my_exit 0
 fi
 
-if [ "x${option}" = "x--resources-dir" ]; then
-    echo "${datatools_resources_dir}"
+if [ "x${option}" = "x--datadir" ]; then
+    echo "${datatools_data_dir}"
+    my_exit 0
+fi
+
+if [ "x${option}" = "x--etcdir" ]; then
+    echo "${datatools_etc_dir}"
+    my_exit 0
+fi
+
+if [ "x${option}" = "x--docdir" ]; then
+    echo "${datatools_doc_dir}"
     my_exit 0
 fi
 
@@ -133,11 +149,8 @@ if [ "x${option}" = "x--cflags" ]; then
 	#echo -n "`boost-config --cflags date_time serialization iostreams filesystem system` "
 	echo -n "`boost-config --cflags` "
         echo -n "`clhep-config --include` "
-	if [ ${with_embedded_kwsys} -eq 0 ]; then
-	    echo -n "`kwsys-config --cflags` "
-	fi
 	echo ""
-    ) | python @CMAKE_INSTALL_PREFIX@/@INSTALL_MISC_DIR@/pkgtools/mkuniqueflags.py 
+    ) | python @CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_DATADIR@/pkgtools/mkuniqueflags.py 
 
     ###) | sed -e "s/-Wstrict-prototypes//g" -e "s/-Wall//g" | python ${datatools_root}/pkgtools.d/mkuniqueflags.py
     my_exit 0
@@ -166,10 +179,7 @@ if [ "x${option}" = "x--libs" ]; then
     if [ "x${option2}" = "x--with-bio" -a ${with_bio} -eq 1 ]; then
 	bio_ldflags=-ldatatools_bio
     fi
-    echo -n "-L${datatools_lib_dir} ${bio_ldflags} -ldatatools "
-    if [ ${with_embedded_kwsys} -eq 1 ]; then
-	echo -n "-lkwsys -lkwsys_c -ldl "
-    fi
+    echo -n "-L${datatools_lib_dir} ${bio_ldflags} -ldatatools -ldatatools_sys -ldl "
     echo
     my_exit 0
 fi
@@ -186,29 +196,37 @@ if [ "x${option}" = "x--ldflags" ]; then
 	#echo -n "`boost-config --ldflags serialization iostreams filesystem system` "
 	echo -n "`boost-config --ldflags` "
 	echo -n "`clhep-config --libs` -lm "
-	if [ ${with_embedded_kwsys} -eq 0 ]; then
-	    echo -n "`kwsys-config --ldflags` -ldl "
-	else
-	    echo -n "-lkwsys -lkwsys_c -ldl "
-	fi
+	echo -n "-ldatatools_sys -ldl "
 	echo ""
-    ) | python @CMAKE_INSTALL_PREFIX@/@INSTALL_MISC_DIR@/pkgtools/mkuniqueflags.py -r
+    ) | python @CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_DATADIR@/pkgtools/mkuniqueflags.py -r
     my_exit 0
+fi
+
+if [ "x${option}" = "x--with-debug" ]; then
+    echo "${with_debug}"
+    if [ "${with_debug}" = "1" ]; then
+	my_exit 0
+    else
+	my_exit 1	
+    fi
 fi
 
 if [ "x${option}" = "x--with-bio" ]; then
     echo "${with_bio}"
-    my_exit 0
-fi
-
-if [ "x${option}" = "x--with-embedded-kwsys" ]; then
-    echo "${with_embedded_kwsys}"
-    my_exit 0
+    if [ "${with_bio}" = "1" ]; then
+	my_exit 0
+    else
+	my_exit 1	
+    fi
 fi
 
 if [ "x${option}" = "x--with-python-wrapper" ]; then
     echo "${with_python_wrapper}"
-    my_exit 0
+    if [ "${with_python_wrapper}" = "1" ]; then
+	my_exit 0
+    else
+	my_exit 1	
+    fi
 fi
 
 if [ "x${option}" = "x--boost-version" ]; then
diff --git a/source/bxdatatools/pkgtools.d/pkgtool b/source/bxdatatools/pkgtools.d/pkgtool
--- a/source/bxdatatools/pkgtools.d/pkgtool
+++ b/source/bxdatatools/pkgtools.d/pkgtool
@@ -15,13 +15,13 @@ function my_exit ()
 appname=${APPNAME} 
 appversion=0.1 
 package_name="datatools"
-list_of_actions="check configure unconfigure build doc test untest clean install uninstall reset list_of_actions"
+list_of_actions="check configure unconfigure build doc test untest clean install uninstall reset quickstart list_of_actions"
 pkgtools_dir="pkgtools.d"
 
 the_base_dir=$(pwd)
 
 if [ ! -d ./${pkgtools_dir} ]; then
-    echo "ERROR: current direcotry is : $(pwd)" >&2
+    echo "ERROR: current directory is : $(pwd)" >&2
     echo "ERROR: ${appname}: Please run this script from the package base directory ! Abort !" >&2  
     my_exit 1
 fi
@@ -217,6 +217,8 @@ while [ -n "$1" ]; do
 	        the_action_mode="${arg}"	
             elif [ "$arg" = "reset" ]; then
 	        the_action_mode="${arg}"	
+            elif [ "$arg" = "quickstart" ]; then
+	        the_action_mode="${arg}"	
             elif [ "$arg" = "list_of_actions" ]; then
 	        the_action_mode="${arg}"	
 	    else
@@ -327,11 +329,14 @@ function do_configure ()
 
     local install_prefix=""
     local reset_build_dir=0
+    local with_debug=0
     local with_bio=1
     local with_doc=1
     local with_test=1
     local with_python_wrapper=0
     local with_dependency_check=0
+    local build_type=
+    local cadfael_cmake_config_dir=
     while [ -n "$1" ]; do
 	local option="$1"
 	#pkgtools__msg_warning "Option: '${option}'"
@@ -344,6 +349,19 @@ function do_configure ()
 	elif [ "${option}" = "--install-prefix" ]; then
 	    shift 1
 	    install_prefix="$1"
+	elif [ "${option}" = "--cadfael-cmake-config-dir" ]; then
+	    shift 1
+	    cadfael_cmake_config_dir="$1"
+	elif [ "${option}" = "--release-build" ]; then
+	    build_type="Release"
+	    with_debug=0
+	elif [ "${option}" = "--debug-build" ]; then
+	    build_type="Debug"
+	    with_debug=1
+	elif [ "${option}" = "--with-debug" ]; then
+	    with_debug=1
+	elif [ "${option}" = "--without-bio" ]; then
+	    with_debug=0
 	elif [ "${option}" = "--with-bio" ]; then
 	    with_bio=1
 	elif [ "${option}" = "--without-bio" ]; then
@@ -367,6 +385,11 @@ function do_configure ()
 	fi
 	shift 1
     done
+
+    if [ "x${build_type}" = "x" ]; then
+	build_type="Release"
+	pkgtools__msg_notice "Using default built type: '${build_type}'."
+    fi
 
     if [ -d ${the_build_dir} ]; then
 	pkgtools__msg_warning "The '${the_build_dir}' build directory already exists !"
@@ -393,6 +416,14 @@ function do_configure ()
     pkgtools__msg_notice "Build directory       : '${the_build_dir}'"
     test -f ${pkgtools_conf} && rm -f ${pkgtools_conf} 
     echo "build_dir=${the_build_dir}" >> ${pkgtools_conf}
+
+    if [ "x${cadfael_cmake_config_dir}" != "x" ]; then
+      if [ ! -f "x${cadfael_cmake_config_dir}" ]; then
+	  pkgtools__msg_error "Cannot find Cadfael CMake configuration file '${cadfael_cmake_config_dir}' !"
+	  __pkgtools__at_function_exit
+	  return 1
+      fi
+    fi
  
     pkgtools__msg_notice "Installation prefix   : '${install_prefix}'"
     pkgtools__msg_notice "With documentation    : '${with_doc}'"
@@ -400,7 +431,10 @@ function do_configure ()
     pkgtools__msg_notice "With Python wrapper   : '${with_python_wrapper}'"
     pkgtools__msg_notice "With Boost I/O DLL    : '${with_bio}'"
     pkgtools__msg_notice "With dependency check : '${with_dependency_check}'"
-
+    pkgtools__msg_notice "Build type            : '${build_type}'"
+    if [ "x${cadfael_cmake_config_dir}" != "x" ]; then
+	pkgtools__msg_notice "Cadfael CMake config  : '${cadfael_cmake_config_dir}'"
+    fi
     if [ ${with_dependency_check} -eq 1 ]; then
 	do_check
 	if [ $? -ne 0 ]; then
@@ -411,13 +445,20 @@ function do_configure ()
     fi
 
     cd ${the_build_dir}
+    local additional_options=
+    if [ "x${cadfael_cmake_config_dir}" != "x" ]; then
+        pkgtools__msg_warning "!!! EXPERIMENTAL FEATURE !!! Passing Cadfael CMake configuration file"
+	additional_options="${additional_options}-DCADFAEL_CMAKE_CONFIG_DIR:PATH=${cadfael_cmake_config_dir} "
+    fi
     cmake \
 	-DCMAKE_INSTALL_PREFIX:PATH=${install_prefix} \
-	-DCMAKE_BUILD_TYPE:STRING=Release \
+	-DCMAKE_BUILD_TYPE:STRING=${build_type} \
+	-DDATATOOLS_WITH_DEBUG=${with_debug} \
+	-DDATATOOLS_WITH_BIO=${with_bio} \
+	-DDATATOOLS_WITH_PYTHON_WRAPPER=${with_python_wrapper} \
 	-DDATATOOLS_WITH_DOC=${with_doc} \
 	-DDATATOOLS_WITH_TEST=${with_test} \
-	-DDATATOOLS_WITH_PYTHON_WRAPPER=${with_python_wrapper} \
-	-DDATATOOLS_WITH_BIO=${with_bio} \
+	${additional_options} \
 	..
     if [ $? -ne 0 ]; then
 	pkgtools__msg_error "Cannot configure the '${package_name}' package !"
@@ -881,6 +922,15 @@ function main ()
 	do_reset $@
 	if [ $? -ne 0 ]; then
 	    pkgtools__msg_error "Reset failed !"
+	    __pkgtools__at_function_exit
+	    return 1
+	fi
+    fi
+    
+    if [ "${action_mode}" = "quickstart" ]; then
+	do_configure $@ && do_build $@ && do_doc $@ && do_test && do_install 
+	if [ $? -ne 0 ]; then
+	    pkgtools__msg_error "Quickstart failed !"
 	    __pkgtools__at_function_exit
 	    return 1
 	fi
