remove datatools legacy transitional support macros

diff --git a/source/bxdpp/cmake/dpp_setup.sh.in b/source/bxdpp/cmake/dpp_setup.sh.in
--- a/source/bxdpp/cmake/dpp_setup.sh.in
+++ b/source/bxdpp/cmake/dpp_setup.sh.in
@@ -63,6 +63,16 @@ function do_dpp_setup ()
     # 	fi
     # fi
 
+    which brio-config >/dev/null 2>&1
+    if [ $? -ne 0 ]; then
+	echo "ERROR: do_dpp_setup: Cannot find brio setup ! Abort !" 1>&2
+	return 1
+    else
+	if [ ${verbose} -ne 0 ]; then
+	    echo "VERBOSE: do_dpp_setup: Found brio." 1>&2
+	fi
+    fi
+
     which cuts-config >/dev/null 2>&1
     if [ $? -ne 0 ]; then
 	echo "ERROR: do_dpp_setup: Cannot find cuts setup ! Abort !" 1>&2
@@ -70,6 +80,16 @@ function do_dpp_setup ()
     else
 	if [ ${verbose} -ne 0 ]; then
 	    echo "VERBOSE: do_dpp_setup: Found cuts." 1>&2
+	fi
+    fi
+
+    which mygsl-config >/dev/null 2>&1
+    if [ $? -ne 0 ]; then
+	echo "ERROR: do_dpp_setup: Cannot find mygsl setup ! Abort !" 1>&2
+	return 1
+    else
+	if [ ${verbose} -ne 0 ]; then
+	    echo "VERBOSE: do_dpp_setup: Found mygsl." 1>&2
 	fi
     fi
      
