fix pb with GSL path

diff --git a/source/bxmygsl/pkgtools.d/mygsl-config b/source/bxmygsl/pkgtools.d/mygsl-config
--- a/source/bxmygsl/pkgtools.d/mygsl-config
+++ b/source/bxmygsl/pkgtools.d/mygsl-config
@@ -67,9 +67,47 @@ Known values for OPTION are:
   --help                print this help then exit
   --version             print version information
   --system              print system
+  --test                print test info
 
 EOF
     exit 1
+fi 
+
+gsl_config_def=$(which gsl-config)
+gsl_version_def=$(${gsl_config_def} --version)
+
+if [ "x${GSL_BASE_DIR}" != "x" ]; then
+    if [ ! -d "${GSL_BASE_DIR}" ]; then
+	echo "$SCRIPTNAME: error: GSL_BASE_DIR='${GSL_BASE_DIR}' is not a valid directory! Abort!" 1>&2
+	exit 1
+    fi
+    gsl_config=$(find ${GSL_BASE_DIR}/bin -mindepth 1 -maxdepth 1 -name "gsl-config")
+    gsl_version=$(${gsl_config} --version)
+else
+    gsl_config=${gsl_config_def}
+    gsl_version=${gsl_version_def}
+fi
+
+gsl_major=$(echo ${gsl_version} | cut -d'.' -f1)
+gsl_minor=$(echo ${gsl_version} | cut -d'.' -f2)
+if [ ${gsl_major} -lt 1 ]; then
+    echo "$SCRIPTNAME: error: GSL version ${gsl_version} is not suitable! Abort!" 1>&2
+    exit 1
+elif [ ${gsl_major} -eq 1 -a ${gsl_minor} -lt 9 ]; then
+	echo "$SCRIPTNAME: error: GSL version ${gsl_version} is not suitable! Abort!" 1>&2
+	exit 1
+fi
+
+if [ "x$opt" = "x--test" ]; then
+cat <<EOF
+mygsl-config tests:
+  Default system GSL version is: ${gsl_version_def}
+  Default system GSL config is:  ${gsl_config_def}
+  Current GSL base directory is: ${GSL_BASE_DIR} (from the GSL_BASE_DIR environment variable)
+  Current GSL version is:        ${gsl_version}
+  Current GSL config is:         ${gsl_config}
+EOF
+    exit 0
 fi 
 
 if [ "x$opt" = "x--system" ]; then
@@ -100,32 +138,6 @@ fi
 if [ "x$opt" = "x--cflags" ]; then
     echo -n "-I${THEPACK_INCLUDEDIR} "  \
          "`gsl-config --cflags` " 
-
-#   test -f ${root_cnf:=$ROOT_BASE_DIR/bin/root-config} || $root_cnf=`which $root-config 2>/dev/null`
-#   test ! -z $root_cnf && echo -n " `$root_cnf --cflags` " || no_pack_list="$no_pack_list $root"
-
-#   test -f ${clhep_cnf:=$CLHEP_BASE_DIR/bin/clhep-config} || $clhep_cnf=`which clhep-config 2>/dev/null`
-#   test ! -z $clhep_cnf && echo -n " `$clhep_cnf --include` " || no_pack_list="$no_pack_list clhep"
-
-#   test -f ${hdf5_cnf=`which hdf5-config 2>/dev/null`}
-#   test ! -z $hdf5_cnf && echo -n " `$hdf5_cnf --include` " || no_pack_list="$no_pack_list hdf5"
-
-#   test -f ${gsl_cnf:=`which gsl-config 2>/dev/null`}
-#   test ! -z $gsl_cnf && echo -n " `$gsl_cnf --cflags` " || no_pack_list="$no_pack_list gsl"
-
-#   test -f ${cernlib_cnf:=`which cernlib 2>/dev/null`}
-#   test ! -z $cernlib_cnf && echo -n " `-Dcfortran` " || no_pack_list="$no_pack_list cernlib"
-
-    test -z $no_pack_list || echo "warning: non found packages: $no_pack_list" 1>&2
-    echo
-
-    ################################################################
-    # Please add here some stuff in order to take into account
-    # external package dependencies; it may looks like:
-    # echo "-I${THEPACK_INCLUDEDIR} " \
-    #      "`XXX-config --include` "  (or --cflags)
-    # where XXX stands for the identifier of the external package 
-    ################################################################
     exit 0
 fi
 
@@ -145,26 +157,9 @@ if [ "x$opt" = "x--libs" ]; then
 fi 
 
 if [ "x$opt" = "x--libs-depends" -o "x$opt" = "x--ldflags" ]; then
-  echo -n "-L${THEPACK_LIBDIR} -lmygsl "  \
+  echo -n "-fPIC -L${THEPACK_LIBDIR} -lmygsl "  \
          "`gsl-config --libs` " \
          " -lm"
-
-#   test -f ${root_cnf:=$ROOT_BASE_DIR/bin/root-config} || $root_cnf=`which $root-config 2>/dev/null`
-#   test ! -z $root_cnf && echo -n " `$root_cnf --libs` " || no_pack_list="$no_pack_list $root"
-
-#   test -f ${clhep_cnf:=$CLHEP_BASE_DIR/bin/clhep-config} || $clhep_cnf=`which clhep-config 2>/dev/null`
-#   test ! -z $clhep_cnf && echo -n " `$clhep_cnf --libs` " || no_pack_list="$no_pack_list clhep"
-
-#   test -f ${hdf5_cnf=`which hdf5-config 2>/dev/null`}
-#   test ! -z $hdf5_cnf && echo -n " `$hdf5_cnf --libs` " || no_pack_list="$no_pack_list hdf5"
-
-#   test -f ${gsl_cnf:=`which gsl-config 2>/dev/null`}
-#   test ! -z $gsl_cnf && echo -n " `$gsl_cnf --libs` " || no_pack_list="$no_pack_list gsl"
-
-#   test -f ${cernlib_cnf:=`which cernlib 2>/dev/null`}
-#   test ! -z $cernlib_cnf && echo -n " `$cernlib_cnf mathlib packlib kernlib graflib pawlib` " || no_pack_list="$no_pack_list $cernlib"
-
-    test -z $no_pack_list || echo "warning: non found packages: $no_pack_list" 1>&2
     echo
 
     ################################################################
