upgrade the pkgtool script and related stuff, set version 1.0 before tagging

diff --git a/source/bxgeomtools/pkgtools.d/geomtools-config b/source/bxgeomtools/pkgtools.d/geomtools-config
--- a/source/bxgeomtools/pkgtools.d/geomtools-config
+++ b/source/bxgeomtools/pkgtools.d/geomtools-config
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # -*- mode: shell-script; -*-
 # geomtools-config
 #
@@ -11,17 +11,27 @@
 # Feel free to modify this file if you use another system
 # to build/install this package (i.e. Autotools).
 #
+#
+# The following environment variables may be set to change 
+# the behaviour of the geomtools-config script:
+#
+# export GEOMTOOLS_LDFLAGS_MODE="hardcoded_shared_lib_path"
+#  will force the usage of hardcoded path name while linking against
+#  a shared library (no use of -LPATH -lLIBNAME option)
+#
+# export GEOMTOOLS_USING_CACHE_FILES=0
+#  will not use the cflags/ldflags cache accelerator files
+#
+
 help=0
 
 SCRIPTNAME="geomtools-config"
 COMP=gcc
 COMPVER=$(${COMP} --version | head -1 | cut -d ' ' -f 3)
-COMPILER=${COMP}${COMPVER}
+COMPILER=-${COMP}${COMPVER}
+COMPILER=
 
-THE_SYSTEM="$(uname -s)-$(uname -m | sed -e 's/ //g')"
-#-${COMPILER}"
-
-##THE_SYSTEM="$(uname -s)-$(uname -m | sed -e 's/ //g')"
+THE_SYSTEM="$(uname -s)-$(uname -m | sed -e 's/ //g')${COMPILER}"
 
 THEPACK_ROOT=/usr/local
 if [ -n "${GEOMTOOLS_ROOT}" ]; then
@@ -45,6 +55,18 @@ elif [ -f "${THEPACK_ROOT}/pkgtools.d/package.info"  ]; then
     THEPACK_VERSION=$version
 fi
 
+using_cache_files=1
+if [ "X${GEOMTOOLS_USING_CACHE_FILES}" = "X0" ]; then
+    using_cache_files=${GEOMTOOLS_USING_CACHE_FILES}
+fi
+cflags_cache=${THEPACK_ROOT}/.cflags.cache
+ldflags_cache=${THEPACK_ROOT}/.ldflags.cache
+
+ldflags_mode=""
+if [ "X${GEOMTOOLS_LDFLAGS_MODE}" != "X" ]; then
+    ldflags_mode="${GEOMTOOLS_LDFLAGS_MODE}"
+fi
+
 opt=$1
 
 if [ "x$opt" = "x" ]; then
@@ -55,8 +77,6 @@ fi
 if [ "x$opt" = "x--help" -o "x$opt" = "x-h" -o "x$opt" = "x-?" ]; then
     help=1
 fi
-
-python_version_flag_file=${THEPACK_ROOT}/gmk/geomtools_python_version.config
 
 if [ $help -eq 1 ]; then
     cat<<EOF
@@ -76,6 +96,8 @@ Known values for OPTION are:
   --help                print this help then exit
   --version             print version information
   --system              print system
+  --check               check dependencies and setup
+  --clean-cache-files   clean compile/link cache files
   --with-python         print if Python module is used
   --python-version      print Python version
 
@@ -98,16 +120,6 @@ if [ "x$opt" = "x--version" ]; then
     exit 0
 fi 
 
-if [ "x$opt" = "x--incdir" ]; then
-    echo "${THEPACK_INCLUDEDIR}" 
-    exit 0
-fi
-
-if [ "x$opt" = "x--include" ]; then
-    echo "-I${THEPACK_INCLUDEDIR} " 
-    exit 0
-fi
-
 if [ "x$opt" = "x--python-version" ]; then
     if [ -f ${python_version_flag_file} ]; then
 	cat ${python_version_flag_file}
@@ -129,22 +141,51 @@ if [ "x$opt" = "x--with-python" ]; then
     exit 0
 fi 
 
-if [ "x$opt" = "x--cflags" ]; then
-    echo -n \
-        "-fPIC " \
-	"-I${THEPACK_INCLUDEDIR} "  \
-        "`datatools-config --cflags` "  \
-        "`clhep-config --include` "  \
-        "`mygsl-config --cflags` " | python ${THEPACK_ROOT}/pkgtools.d/mkuniqueflags.py
-    echo
+if [ "x$opt" = "x--clean-cache-files" ]; then
+    if [ -f ${cflags_cache} ]; then
+	echo "${SCRIPTNAME}: NOTICE: Removing '${cflags_cache}' cache file !" >&2
+	rm -f ${cflags_cache}
+    fi
+    if [ -f ${ldflags_cache} ]; then
+	echo "${SCRIPTNAME}: NOTICE: Removing '${ldflags_cache}' cache file !" >&2
+	rm -f ${ldflags_cache}
+    fi
+    exit 0
+fi
 
-    ################################################################
-    # Please add here some stuff in order to take into account
-    # external package dependencies; it may looks like:
-    # echo "-I${THEPACK_INCLUDEDIR} " \
-    #      "`XXX-config --include` "  (or --cflags)
-    # where XXX stands for the identifier of the external package 
-    ################################################################
+if [ "x$opt" = "x--incdir" ]; then
+    echo "${THEPACK_INCLUDEDIR}" 
+    exit 0
+fi
+
+if [ "x$opt" = "x--include" ]; then
+    echo "-I${THEPACK_INCLUDEDIR} " 
+    exit 0
+fi
+
+if [ "x$opt" = "x--cflags" ]; then
+    generate_cflags=0
+    if [ ${using_cache_files} -eq 1 ]; then
+	if [ -f ${cflags_cache} ]; then
+	    cat ${cflags_cache}
+	    exit 0
+	else
+	    generate_cflags=1
+	fi
+    else
+	generate_cflags=1
+    fi
+	    
+    if [ ${generate_cflags} -eq 1 ]; then
+	(
+	    echo -n \
+		"-fPIC " \
+		"-I${THEPACK_INCLUDEDIR} "  \
+		"`datatools-config --cflags` "  \
+		"`mygsl-config --cflags` "  \
+	    | python ${THEPACK_ROOT}/pkgtools.d/mkuniqueflags.py	    
+	) | tee ${cflags_cache}
+    fi
     exit 0
 fi
 
@@ -164,23 +205,46 @@ if [ "x$opt" = "x--libs" ]; then
 fi 
 
 if [ "x$opt" = "x--libs-depends" -o "x$opt" = "x--ldflags" ]; then
-    echo -n "-L${THEPACK_LIBDIR} -lgeomtools "  \
-        "`datatools-config --ldflags` "  \
-        "`clhep-config --libs` "  \
-        "`mygsl-config --ldflags` " | python ${THEPACK_ROOT}/pkgtools.d/mkuniqueflags.py -r
-    echo
-
-    ################################################################
-    # Please add here some stuff in order to take into account
-    # external package dependencies; it may looks like:
-    # echo "-L${THEPACK_LIBDIR} -lgeomtools " \
-    #      "`XXX-config --libs` " 
-    # where XXX stands for the identifier of the external package 
-    ################################################################
+    generate_ldflags=0
+    if [ ${using_cache_files} -eq 1 ]; then
+	if [ -f ${ldflags_cache} ]; then
+	    cat ${ldflags_cache}
+	    exit 0
+	else
+	    generate_ldflags=1
+	fi
+    else
+	generate_ldflags=1
+    fi
+    
+    if [ ${generate_ldflags} -eq 1 ]; then	
+	(
+	    (
+		if [ "X${ldflags_mode}" = "Xhardcoded_shared_lib_path" ]; then
+		    echo -n "${THEPACK_LIBDIR}/libgeomtools.so "
+		else
+		    echo -n "-L${THEPACK_LIBDIR} -lgeomtools "
+		fi
+		echo -n ""  \
+		    "`datatools-config --ldflags` "  \
+		    "`mygsl-config --ldflags` "  \
+		    ) | python ${THEPACK_ROOT}/pkgtools.d/mkuniqueflags.py -r
+	    #echo
+	) | tee ${ldflags_cache}
+    fi
     exit 0
 fi 
 
-echo "$SCRIPTNAME: error: Unknown option!" 
+if [ "x$opt" = "x--check" ]; then
+    ${THEPACK_ROOT}/pkgtools.d/pkgtool check
+    if [ $? -ne 0 ]; then
+	echo "$SCRIPTNAME: error: Check procedure failed!" >&2
+	exit 1
+    fi
+    exit 0
+fi 
+
+echo "$SCRIPTNAME: error: Unknown option '${opt}'!"  >&2
 $0 --help
 exit 1
 
