some update and new material_geom_plugin

diff --git a/source/bxmaterials/cmake/materials_setup.sh.in b/source/bxmaterials/cmake/materials_setup.sh.in
--- a/source/bxmaterials/cmake/materials_setup.sh.in
+++ b/source/bxmaterials/cmake/materials_setup.sh.in
@@ -14,13 +14,8 @@ function do_materials_print_info ()
 	echo "${indent}MATERIALS_NAME                = '${MATERIALS_NAME}'" 1>&2
 	echo "${indent}MATERIALS_VERSION             = '${MATERIALS_VERSION}'" 1>&2
 	echo "${indent}MATERIALS_WITH_DEBUG          = ${MATERIALS_WITH_DEBUG}" 1>&2
-	if [ "x0" = "x1" ]; then	
-	    echo "${indent}MATERIALS_WITH_BIO            = ${MATERIALS_WITH_BIO}" 1>&2
-	fi
-	if [ "x0" = "x1" ]; then	
-	    echo "${indent}MATERIALS_WITH_PYTHON_WRAPPER = ${MATERIALS_WITH_PYTHON_WRAPPER}" 1>&2
-	    echo "${indent}Python module path = @CMAKE_INSTALL_FULL_PYTHONDIR@" 1>&2
-	fi
+	echo "${indent}MATERIALS_WITH_BIO            = ${MATERIALS_WITH_BIO}" 1>&2
+	echo "${indent}MATERIALS_WITH_REFLECTION     = ${MATERIALS_WITH_REFLECTION}" 1>&2
 	echo "${indent}MATERIALS_BIN_DIR             = '${MATERIALS_BIN_DIR}'"
 	echo "${indent}MATERIALS_ETC_DIR             = '${MATERIALS_ETC_DIR}'"
 	echo "${indent}MATERIALS_LIB_DIR             = '${MATERIALS_LIB_DIR}'"
@@ -55,7 +50,19 @@ function do_materials_setup ()
 	echo "WARNING: do_materials_setup: materials is already setup !" 1>&2
 	return 2
     fi 
- 
+
+    if [ "x@MATERIALS_WITH_REFLECTION@" = "x1" ]; then
+	which camp-config >/dev/null 2>&1
+	if [ $? -ne 0 ]; then
+	    echo "ERROR: do_materials_setup: Cannot find CAMP setup ! Abort !" 1>&2
+	    return 1
+	else
+	    if [ ${verbose} -ne 0 ]; then
+		echo "VERBOSE: do_materials_setup: Found CAMP." 1>&2
+	    fi
+	fi
+    fi
+
     # which clhep-config >/dev/null 2>&1
     # if [ $? -ne 0 ]; then
     # 	echo "ERROR: do_materials_setup: Cannot find CLHEP setup ! Abort !" 1>&2
@@ -66,32 +73,20 @@ function do_materials_setup ()
     # 	fi
     # fi
 
-    # if [ "x0" = "x1" ]; then	
-    # 	which datatools-config >/dev/null 2>&1
-    # 	if [ $? -ne 0 ]; then
-    # 	    echo "ERROR: do_materials_setup: Cannot find datatools setup ! Abort !" 1>&2
-    # 	    return 1
-    # 	else
-    # 	    if [ ${verbose} -ne 0 ]; then
-    # 		echo "VERBOSE: do_materials_setup: Found datatools." 1>&2
-    # 	    fi
-    # 	fi
-    # fi
-
-    # which yyy-config >/dev/null 2>&1
-    # if [ $? -ne 0 ]; then
-    # 	echo "ERROR: do_materials_setup: Cannot find yyy setup ! Abort !" 1>&2
-    # 	return 1
-    # else		
-    # 	if [ ${verbo	se} -ne 0 ]; then
-    # 	    echo "VERBOSE: do_materials_setup: Found yyy." 1>&2
-    # 	fi
-    # fi
-    
+    which geomtools-config >/dev/null 2>&1
+    if [ $? -ne 0 ]; then
+	echo "ERROR: do_materials_setup: Cannot find geomtools setup ! Abort !" 1>&2
+	return 1
+    else
+	if [ ${verbose} -ne 0 ]; then
+	    echo "VERBOSE: do_materials_setup: Found geomtools." 1>&2
+	fi
+    fi
+     
     export MATERIALS_ROOT="@CMAKE_INSTALL_PREFIX@"
     export MATERIALS_ROOT_DIR="@CMAKE_INSTALL_PREFIX@"
-    export MATERIALS_NAME="@materials_PACKAGE_NAME@"
-    export MATERIALS_VERSION="@materials_VERSION_STR@"
+    export MATERIALS_NAME="@PROJECT_NAME@"
+    export MATERIALS_VERSION="@materials_VERSION@"
     export MATERIALS_BIN_DIR="@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_BINDIR@"
     export MATERIALS_ETC_DIR="@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_ETCDIR@"
     export MATERIALS_LIB_DIR="@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@"
@@ -99,13 +94,9 @@ function do_materials_setup ()
     export MATERIALS_INCLUDE_DIR="@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_INCLUDEDIR@"
     export MATERIALS_DATA_DIR="@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_DATADIR@"
     export MATERIALS_WITH_DEBUG=@MATERIALS_WITH_DEBUG@
-    if [ "x0" = "x1" ]; then	
-	export MATERIALS_WITH_BIO=@MATERIALS_WITH_BIO@
-    fi
-    if [ "x0" = "x1" ]; then	
-	export MATERIALS_WITH_PYTHON_WRAPPER=@MATERIALS_WITH_PYTHON_WRAPPER@
-    fi
-    export MATERIALS_CMAKE_CONFIG_DIR="@CMAKE_INSTALL_PREFIX@/@materials_cmake_config_install_dir@"
+    export MATERIALS_WITH_BIO=@MATERIALS_WITH_BIO@
+    export MATERIALS_WITH_REFLECTION=@MATERIALS_WITH_REFLECTION@
+    export MATERIALS_CMAKE_CONFIG_DIR="@CMAKE_INSTALL_PREFIX@/@_materials_cmake_config_install_dir@"
 
     if [ -n "${PATH}" ]; then
 	export PATH="${MATERIALS_BIN_DIR}:${PATH}"
@@ -119,33 +110,6 @@ function do_materials_setup ()
 	export @_ld_library_path_env@="${MATERIALS_LIB_DIR}"
     fi 
 
-    if [ "x@MATERIALS_WITH_PKGCONFIG@" = "xON" -o "x@MATERIALS_WITH_PKGCONFIG@" = "x1" ]; then
-	if [ -n "${PKG_CONFIG_PATH}" ]; then 
-            export PKG_CONFIG_PATH="@_materials_pkgconfig_install_dir@:${PKG_CONFIG_PATH}"
-	else
-            export PKG_CONFIG_PATH="@_materials_pkgconfig_install_dir@"
-	fi
-    fi
-
-    if [ "x0" = "x1" ]; then	
-	if [ "x@MATERIALS_WITH_PYTHON_WRAPPER@" = "xON" ]; then
-     	    # update Python path...
-	    if [ -n "${PYTHONPATH}" ]; then 
-		export PYTHONPATH="@CMAKE_INSTALL_FULL_PYTHONDIR@:${PYTHONPATH}"
-	    else
-		export PYTHONPATH="@CMAKE_INSTALL_FULL_PYTHONDIR@"
-	    fi
-	fi
-    fi
-
-    if [ "x@MATERIALS_WITH_CMAKE_FIND_MODULE@" = "xON" -o "x@MATERIALS_WITH_CMAKE_FIND_MODULE@" = "x1" ]; then
-	if [ -n "${CMAKE_MODULE_PATH}" ]; then 
-            export CMAKE_MODULE_PATH="@CMAKE_INSTALL_PREFIX@/@materials_find_module_install_dir@:${CMAKE_MODULE_PATH}"
-	else
-            export CMAKE_MODULE_PATH="@CMAKE_INSTALL_PREFIX@/@materials_find_module_install_dir@"
-	fi
-    fi
-
     if [ ${verbose} -gt 1 ]; then
 	do_materials_print_info "VERBOSE: do_materials_setup"
     fi
@@ -156,8 +120,7 @@ function do_materials_setup ()
     return 0
 }
 typeset -fx do_materials_setup
-alias materials_setup='do_materials_setup'
 
-echo "NOTICE: do_materials_setup: Please setup materials with 'do_materials_setup'." 1>&2
+echo "NOTICE: do_materials_setup: Please setup 'materials' with 'do_materials_setup'." 1>&2
 
 # end of materials_setup.sh
